export const DEFAULT_EQUIPMENT = [
  {
    id: "eq-1",
    name: "Hot Plate Magnetic Stirrer",
    category: "Heating & Mixing",
    shortName: "Hot Plate",
    icon: "♨",
    type: "stirrer",
    isDefault: true,
  },
  {
    id: "eq-2",
    name: "Centrifuge",
    category: "Separation",
    shortName: "Centrifuge",
    icon: "◉",
    type: "centrifuge",
    isDefault: true,
  },
  {
    id: "eq-3",
    name: "pH Meter",
    category: "Measurement",
    shortName: "pH Meter",
    icon: "⌁",
    type: "ph",
    isDefault: true,
  },
  {
    id: "eq-4",
    name: "Weight Balance",
    category: "Measurement",
    shortName: "Weight Balance",
    icon: "⚖",
    type: "balance",
    isDefault: true,
  },
  {
    id: "eq-5",
    name: "UV-Vis Spectrophotometer",
    category: "Analysis",
    shortName: "UV-Vis",
    icon: "◈",
    type: "spectro",
    isDefault: true,
  },
];
